### PR TITLE
Feature/license

### PR DESCRIPTION
**Pull request by jadunham1**
Adding license

### CODE REVIEW

**Comment by enarciso** [comment]
Looks good, Can you update your README witht he `Contributor/Author` section? I'll update with an example

**Comment by enarciso** [comment]
```

**Comment by enarciso** [comment]
```## Contributing

1. Fork it ( https://github.com/[my-github-username]/mixlib-install/fork )
2. Create your feature branch (`git checkout -b my-new-feature`)
3. Commit your changes (`git commit -am 'Add some feature'`)
4. Push to the branch (`git push origin my-new-feature`)
5. Create a new Pull Request```

**Comment by jadunham1** [comment]
Don't worry about this failing, it's failing flake8 changes atm, it's still in active development.
This will move over to something like travis ci instead of our internal build systems as well which is where this is failing.

**Pull request merged**
